name: islam_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  hijri: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/images/logo.png

  uses-material-design: true
