name: religion
description: "A Islamic Religion Information App"

publish_to: "none" # Remove this line if you
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  hijri: ^3.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  prayers_times: ^0.0.6
  adhan: ^2.0.0-nullsafety.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: TiroBangla
      fonts:
        - asset: assets/fonts/TiroBangla-Regular.ttf
        - asset: assets/fonts/TiroBangla-Italic.ttf
          style: italic
  assets:
    - assets/images/
  uses-material-design: true
