name: religion
description: "A Islamic Religion Information App"

publish_to: "none" # Remove this line if you
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  hijri: ^3.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  prayers_times: ^0.0.6
  adhan: ^2.0.0-nullsafety.2
  table_calendar: ^3.2.0
  quran: ^1.3.3
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  url_launcher_platform_interface: ^2.3.0
  shimmer: ^3.0.0

  # google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" # Your icon file path
  # adaptive_icon_background: "#ffffff" # For Android adaptive icons (optional)
  # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # (optional)

flutter:
  fonts:
    - family: LalSalu
      fonts:
        - asset: assets/fonts/Lal_Salu_Normal.ttf
        - asset: assets/fonts/Lal_Salu_Bold.ttf

  assets:
    - assets/images/
  uses-material-design: true
